version: "3"
services:
  build:
    build:
      context: .
      dockerfile: docker/build/Dockerfile
    env_file: ./docker/build/.env
    volumes:
      - ./build:/home/node/build
  web:
    image: nginx
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=fng.testingmagic.ovh
    volumes:
      - ./build:/usr/share/nginx/html
networks:
  default:
    external:
      name: nginx-proxy
